### ISSUE TITLE
Github Pages Jekyll Build Fail

### ISSUE THREAD

**Issue by hallahan** [posm/OpenMapKitWebsite#30]
When merging `dist` into `gh-pages`, the latest Github Pages Jekyll build fails, yet there are no problems when building locally. One option is I can just turn the `dist` branch into `gh-pages` and no longer have Github do the build, since this sort of problem is quite common with Github pages.

cc/ @danielduhh 

I get the following email:

---

The page build failed with the following error:

The tag `markdown` on line 8 in `docs_additionalresources.html` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by danielduhh** [comment]
This looks like the same error as #12

**Comment by danbjoseph** [comment]
docs are going to be rebuilt and combined with posm docs
